# Building a PR Review Agent. Stage 3/5
# Commentor Agent
#
# In this stage, we extend our workflow by adding a second agent.
# Previously, we used tools to retrieve context from a GitHub repository.
# Now, we introduce a CommentorAgent that uses the gathered context
# to generate a final PR review comment.
#
# Since we now have two agents (ContextAgent and CommentorAgent),
# we must maintain shared state so they can communicate effectively.
# We also use AgentWorkflow to orchestrate handoffs between agents.
#
# ------------------------------------------------------------
# STATE MANAGEMENT
# ------------------------------------------------------------
#
# We maintain the following keys in state:
#
# - "gathered_contexts": the context collected by ContextAgent
# - "draft_comment": the first draft review generated by CommentorAgent
#
# After ContextAgent gathers all required information and creates a summary,
# it must store it in the state using a tool.
#
# Similarly, after CommentorAgent generates a draft review comment,
# it must store it in the state using another tool.
#
# Example logic for saving draft_comment to state:
#
# current_state = await ctx.get("state")
# current_state["draft_comment"] = draft_comment
# await ctx.set("state", current_state)
#
# Both state update functions must be added to the corresponding agent’s tools list.
#
# ------------------------------------------------------------
# COMMENTOR AGENT
# ------------------------------------------------------------
#
# Create a new FunctionAgent called "CommentorAgent".
#
# Purpose:
# - Uses gathered context to generate a ~200–300 word PR review comment.
# - Writes review comments as a human reviewer would.
#
# System Prompt:
#
# You are the commentor agent that writes review comments for pull requests
# as a human reviewer would.
#
# Ensure to:
#  - Request PR details, changed files, and any other needed files
#    from the ContextAgent.
#  - After gathering everything needed, write a ~200–300 word review
#    in markdown format including:
#       - What is good about the PR?
#       - Did the author follow ALL contribution rules? What is missing?
#       - Are there tests for new functionality?
#         If there are new models, are there migrations?
#         (Use the diff to determine this.)
#       - Are new endpoints documented?
#         (Use the diff to determine this.)
#       - Which lines could be improved?
#         Quote those lines and suggest improvements.
#  - If additional details are required, hand off to ContextAgent.
#  - Directly address the author in a natural tone.
#
# Agent configuration:
#
# llm=llm,
# name="CommentorAgent",
# description="Uses the context gathered by the context agent to draft a pull review comment.",
# tools=[add_comment_to_state],
# can_handoff_to=["ContextAgent"]
#
# This agent only needs the state management function
# for saving draft_comment into state.
#
# ------------------------------------------------------------
# CONTEXT AGENT
# ------------------------------------------------------------
#
# The existing ContextAgent must now:
#
# 1. Be converted into a FunctionAgent (not ReActAgent).
# 2. Be equipped with the new state management tool (add_context_to_state).
# 3. Have a clear description.
# 4. Include a system prompt.
# 5. Be able to hand control back to CommentorAgent.
#
# Updated System Prompt:
#
# You are the context gathering agent.
# When gathering context, you MUST gather:
#   - PR details: author, title, body, diff_url, state, head_sha
#   - Changed files
#   - Any requested files
#
# Once all requested information is gathered,
# you MUST hand control back to the CommentorAgent.
#
# Agent configuration:
#
# context_agent = FunctionAgent(
#     llm=llm,
#     name="ContextAgent",
#     description="Gathers all necessary PR details, changed files, and requested repository files.",
#     tools=[..., add_context_to_state],
#     system_prompt=...,
#     can_handoff_to=["CommentorAgent"]
# )
#
# ------------------------------------------------------------
# WORKFLOW ORCHESTRATION
# ------------------------------------------------------------
#
# Use AgentWorkflow to orchestrate communication between the two agents.
#
# Provide:
#  - Both agents
#  - The root agent (CommentorAgent starts first)
#  - Initial state
#
# workflow_agent = AgentWorkflow(
#     agents=[context_agent, commentor_agent],
#     root_agent=commentor_agent.name,
#     initial_state={
#         "gathered_contexts": "",
#         "draft_comment": ""
#     },
# )
#
# Note:
# The workflow begins with CommentorAgent.
#
# ------------------------------------------------------------
# RUNNING THE WORKFLOW
# ------------------------------------------------------------
#
# Import required classes:
#
# from llama_index.core.agent.workflow import AgentOutput, ToolCall, ToolCallResult
# import asyncio
#
# Create an async main() function:
#
# async def main():
#     query = input().strip()
#     prompt = RichPromptTemplate(query)
#
#     handler = workflow_agent.run(prompt.format())
#
#     current_agent = None
#     async for event in handler.stream_events():
#
#         # Detect agent switch
#         if hasattr(event, "current_agent_name") and event.current_agent_name != current_agent:
#             current_agent = event.current_agent_name
#             print(f"Current agent: {current_agent}")
#
#         # Agent output
#         elif isinstance(event, AgentOutput):
#             if event.response.content:
#                 print("\n\nFinal response:", event.response.content)
#             if event.tool_calls:
#                 print("Selected tools:", [call.tool_name for call in event.tool_calls])
#
#         # Tool result
#         elif isinstance(event, ToolCallResult):
#             print(f"Output from tool: {event.tool_output}")
#
#         # Tool call
#         elif isinstance(event, ToolCall):
#             print(f"Calling selected tool: {event.tool_name}, with arguments: {event.tool_kwargs}")
#
#
# if __name__ == "__main__":
#     asyncio.run(main())
#     git.close()
#
# ------------------------------------------------------------
# EXPECTED WORKFLOW BEHAVIOR
# ------------------------------------------------------------
#
# Example input:
#
# > A new PR number 100 has been created. Write a review for it.
#
# Expected output flow:
#
# Current agent: CommentorAgent
# Selected tools: ['handoff']
# Calling selected tool: handoff, with arguments: {...}
# Output from tool: Agent ContextAgent is now handling the request ...
#
# Current agent: ContextAgent
# ... context gathering operations ...
# Selected tools: ['handoff']
# Output from tool: Agent CommentorAgent is now handling the request ...
#
# Current agent: CommentorAgent
# ... comment generation actions ...
#
# ------------------------------------------------------------
# OBJECTIVES SUMMARY
# ------------------------------------------------------------
#
# 1. Add two state management functions:
#    - add_context_to_state
#    - add_comment_to_state
#
# 2. Create CommentorAgent:
#    - Uses gathered context
#    - Generates ~200–300 word PR review
#    - Saves draft_comment to state
#    - Can hand off to ContextAgent
#
# 3. Update ContextAgent:
#    - Convert to FunctionAgent
#    - Add state tool
#    - Add system prompt
#    - Add description
#    - Enable handoff to CommentorAgent
#
# 4. Orchestrate both agents with AgentWorkflow:
#    - Provide agents
#    - Set root_agent
#    - Initialize state
#
# 5. Accept input
# 6. Run workflow
# 7. Stream outputs
# 8. Ensure tool calls and handoffs appear in output
#
# ------------------------------------------------------------
# IMPORTANT TEST NOTE
# ------------------------------------------------------------
#
# Do NOT add characters to the PR title or body that would
# force double quotes in the returned string.
# Some tests expect single quotes in PR parameters.
#
# ------------------------------------------------------------

# Required dependencies:
# pip install llama-index-core pydantic python-dotenv pygithub openai

import asyncio
import os
from typing import Any, Dict, List

import dotenv
from github import Auth, Github

from llama_index.core.agent.workflow import (
    AgentOutput,
    AgentWorkflow,
    FunctionAgent,
    ToolCall,
    ToolCallResult,
)
from llama_index.core.prompts import RichPromptTemplate
from llama_index.core.tools import FunctionTool
from llama_index.core.workflow import Context
from llama_index.llms.openai import OpenAI

dotenv.load_dotenv()

repo_url = "https://github.com/alexander-morrison/recipes-api.git"

github_token = os.getenv("GITHUB_TOKEN")
if not github_token:
    raise ValueError("GITHUB_TOKEN environment variable is not set.")

git = Github(auth=Auth.Token(github_token))


def get_repo():
    name = repo_url.split("/")[-1].replace(".git", "")
    user = repo_url.split("/")[-2]
    return git.get_repo(f"{user}/{name}")


def get_pr_details(pr_number: int) -> Dict[str, Any]:
    repo = get_repo()
    pr = repo.get_pull(pr_number)
    body = pr.body if pr.body not in (None, "") else "No description provided."
    return {
        "author": pr.user.login if pr.user else None,
        "title": pr.title,
        "body": body,
        "diff_url": pr.diff_url,
        "state": pr.state,
        "head_sha": pr.head.sha if pr.head else None,
        "commit_shas": [c.sha for c in pr.get_commits()],
    }


def get_changed_files(pr_number: int) -> List[Dict[str, Any]]:
    repo = get_repo()
    pr = repo.get_pull(pr_number)
    out: List[Dict[str, Any]] = []
    for f in pr.get_files():
        out.append(
            {
                "filename": f.filename,
                "status": f.status,
                "additions": f.additions,
                "deletions": f.deletions,
                "changes": f.changes,
                "patch": f.patch,
            }
        )
    return out


def get_file_contents(path: str) -> str:
    repo = get_repo()
    blob = repo.get_contents(path)
    return blob.decoded_content.decode("utf-8")


def get_commit_details(commit_sha: str) -> Dict[str, Any]:
    repo = get_repo()
    c = repo.get_commit(commit_sha)
    files: List[Dict[str, Any]] = []
    for f in c.files:
        files.append(
            {
                "filename": f.filename,
                "status": f.status,
                "additions": f.additions,
                "deletions": f.deletions,
                "changes": f.changes,
                "patch": f.patch,
            }
        )
    return {"sha": c.sha, "changed_files": files}


async def add_context_to_state(ctx: Context, gathered_contexts: str) -> str:
    state = await ctx.get("state")
    state["gathered_contexts"] = gathered_contexts
    await ctx.set("state", state)
    return "State updated with gathered contexts."


async def add_comment_to_state(ctx: Context, draft_comment: str) -> str:
    state = await ctx.get("state")
    state["draft_comment"] = draft_comment
    await ctx.set("state", state)
    return "State updated with draft comment."


get_pr_details_tool = FunctionTool.from_defaults(get_pr_details, name="get_pr_details")
get_changed_files_tool = FunctionTool.from_defaults(get_changed_files, name="get_changed_files")
get_file_contents_tool = FunctionTool.from_defaults(get_file_contents, name="get_file_contents")
get_commit_details_tool = FunctionTool.from_defaults(get_commit_details, name="get_commit_details")
add_context_to_state_tool = FunctionTool.from_defaults(add_context_to_state, name="add_context_to_state")
add_comment_to_state_tool = FunctionTool.from_defaults(add_comment_to_state, name="add_comment_to_state")

llm = OpenAI(
    model=os.getenv("OPENAI_MODEL", "gpt-4"),
    api_key=os.getenv("OPENAI_API_KEY"),
    api_base=os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1"),
)

context_agent = FunctionAgent(
    llm=llm,
    name="ContextAgent",
    description="Gathers all necessary PR details, changed files, and requested repository files.",
    tools=[
        get_pr_details_tool,
        get_changed_files_tool,
        get_file_contents_tool,
        get_commit_details_tool,
        add_context_to_state_tool,
    ],
    system_prompt=(
        "You are the context gathering agent.\n"
        "When gathering context, you MUST gather:\n"
        "  - PR details: author, title, body, diff_url, state, head_sha\n"
        "  - Changed files\n"
        "  - Any requested files\n"
        "Once all requested information is gathered, you MUST hand control back to the CommentorAgent."
    ),
    can_handoff_to=["CommentorAgent"],
)

commentor_agent = FunctionAgent(
    llm=llm,
    name="CommentorAgent",
    description="Uses the context gathered by the context agent to draft a pull review comment.",
    tools=[add_comment_to_state_tool],
    system_prompt=(
        "You are the commentor agent that writes review comments for pull requests "
        "as a human reviewer would.\n"
        "Ensure to:\n"
        "  - Request PR details, changed files, and any other needed files from the ContextAgent.\n"
        "  - After gathering everything needed, write a ~200–300 word review in markdown format including:\n"
        "       - What is good about the PR?\n"
        "       - Did the author follow ALL contribution rules? What is missing?\n"
        "       - Are there tests for new functionality? If there are new models, are there migrations? "
        "(Use the diff to determine this.)\n"
        "       - Are new endpoints documented? (Use the diff to determine this.)\n"
        "       - Which lines could be improved? Quote those lines and suggest improvements.\n"
        "  - If additional details are required, hand off to ContextAgent.\n"
        "  - Directly address the author in a natural tone."
    ),
    can_handoff_to=["ContextAgent"],
)

workflow_agent = AgentWorkflow(
    agents=[context_agent, commentor_agent],
    root_agent=commentor_agent.name,
    initial_state={"gathered_contexts": "", "draft_comment": ""},
)


async def main():
    query = input().strip()
    prompt = RichPromptTemplate(query)
    handler = workflow_agent.run(prompt.format())

    current_agent = None
    async for event in handler.stream_events():
        if hasattr(event, "current_agent_name") and event.current_agent_name != current_agent:
            current_agent = event.current_agent_name
            print(f"Current agent: {current_agent}")

        elif isinstance(event, AgentOutput):
            if event.response.content:
                print("\n\nFinal response:", event.response.content)
            if event.tool_calls:
                print("Selected tools:", [call.tool_name for call in event.tool_calls])

        elif isinstance(event, ToolCallResult):
            print(f"Output from tool: {event.tool_output}")

        elif isinstance(event, ToolCall):
            print(f"Calling selected tool: {event.tool_name}, with arguments: {event.tool_kwargs}")


if __name__ == "__main__":
    asyncio.run(main())
    git.close()
